site_name: Documentation Onebeat Brazil

theme:
  name: material
  palette:
  - scheme: default
    primary: deep blue
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  - scheme: slate
    primary: deep blue
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  features:
  - search.suggest
  - search.highlight
  icon:
    repo: fontawesome/brands/github-alt
#  logo: img/icon-white.svg
#  favicon: img/favicon.png
  language: en
nav:
  - Home: index.md
  - Overview Onebeat: Overview_Onebeat.md
  - Abertura de tasks: Abertura_de_tasks.md 
  - Automatizar o delete de backup dos bancos: Automatizar_delete_backup_dos_bancos.md
  - Como Reprocessar uma Carga: Reprocessar_Carga.md
  - Configurar filezila: Configurar_filezila.md
  - Corrigir erro no PBI: Erro_PBI.md
  - Criar sp_BissHistory: Criar_sp_BissHistory.md
  - Instalação da licença: Ativacao_licenca.md
  - Integrar Shared Project: Integrar_Shared_Project.md
  - Shared Project: Shared_Project.md
  - Solução de Proporcionalidade Pai-Filho (solution_multiples): Solucao_Proporcionalidade_Pai_Filho_solution_multiples.md
  - Verificar os erros no email: Erros_no_email.md
